# Generated by Django 2.2.9 on 2020-01-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('access_token', models.TextField()),
            ],
        ),
    ]
