# Generated by Django 2.2.9 on 2020-01-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
