# Generated by Django 2.2.9 on 2020-01-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vkapi', '0002_profile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
