# Generated by Django 2.2.9 on 2020-01-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapi', '0003_remove_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vk_id',
            field=models.TextField(unique='true'),
        ),
    ]
